openapi: 3.0.0

info:
  title: Hat API
  description: These endpoints are for the hat decorator API.
  version: "1.0"

servers:
  - url: "/api"

paths:
  /hat:
    post:
      operationId: put_hat_on
      tags:
        - hats
      description: Returns a url to your avatar with a hat
      requestBody:
        description: the file to upload
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                body:
                  type: string
                  format: binary
      responses:
        "200":
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HatResponseDTO"

components:
  schemas:
    HatResponseDTO:
      properties:
        image_url:
          type: string
      required:
        - image_url

    Error:
      properties:
        data:
          type: object
        message:
          type: string
      required:
        - message
