openapi: 3.0.0

info:
  title: Hat API
  description: These endpoints are for the hat decorator API.
  version: "1.0"

servers:
  - url: "localhost:3000/hats"

paths:
  /hat:
    post:
      operationId: put_hat_on
      tags:
        - hats
      description: Returns a url to your avatar with a hat
      requestBody:
        description: the file to upload
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/HatRequestDTO"
      responses:
        "200":
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HatResponseDTO"

components:
  schemas:
    HatRequestDTO:
      type: object
      properties:
        body:
          type: string
          format: binary
    HatResponseDTO:
      properties:
        image_url:
          type: string
      required:
        - image_url

    Error:
      properties:
        data:
          type: object
        message:
          type: string
      required:
        - message
