on: [push, pull_request]
name: Website Linting
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.7"
      - run: cd website
      - run: npm install
      - run: npm run lint
